name: Matrix Demonstration
on: push
jobs:
   build:
    continue-on-error: true
    strategy: 
      matrix:
      # This will create multiple jobs with the below combination
      # 6 jobs will be create in the below case 
      # [v12, ubuntu],[v12, windows],[v14, ubuntu],[v14, windows],[v16, ubuntu],[v16, windows] 
      # if any of the builds fail then entire jobs will fail.
        node-version: [12,14,16]
        os: [ubuntu-latest, windows-latest]
      # Include will only let the below configured version to execute apart from the above matrix.
        include:
          - node-version: 18
            operating-system: ubuntu-latest
      # Exclude will omiit the following version to be executed from the above matrix.
        exclude:
          - node-version: 12
            operating-system: windows-latest   
    runs-on: ${{matrix.os}}
    steps:
    - name: checkout the code
      uses : actions/checkout@v3
    - name: Install Node
      uses : actions/setup-node@v3
      with : 
        node-version: ${{matrix.node-version}}
    - name : Install dependencies
      run : npm ci
    - name : build project
      run : npm run build



  