name: Reusable Workflow Deployment
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: "Output files"
        required: false
        default: dist
        type: string
        
jobs:
  deploy:
  
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with: 
          name: ${{inputs.artifact-name}}
      - name: Output Information
        run : echo " Deploying and uploading"

